#!/bin/sh
# script to start Rserve with the configuration FastRWeb/code/rserve.conf
# add -d if you want to start the debugging version
#
# honored environment variables:
# ROOT     - root of the RCloud installation (mandatory, although there is a feeble fallback attempt)
# RBIN     - path to R binary to be run (optional, default is "R")

if [ -z "$ROOT" ]; then ## some auto-detection if ROOT is not set...
    for c in /data/rcloud /data/ws /var/www/ws /var/FastRWeb /data/FastRWeb "`pwd`"; do
	if [ -e "$c/code/rserve.conf" ]; then
	    ROOT="$c"
	    break
	fi
    done
fi

if [ -z "$ROOT" ]; then
    echo '' >&2
    echo ' ERROR: cannot determine ROOT - please set accordingly' >&2
    echo '' >&2
    exit 1
fi
export ROOT

: ${RBIN=R}

if [ "$1" = -h ]; then
  echo ''
  echo " Usage: $0 [-d]"
  echo ''
  echo ' You may need to set ROOT and optionally RBIN accordingly'
  echo ''
  exit 0
fi

if [ "$1" = -d ]; then
  PX=.dbg
fi

# --vanilla is intentional - use code/rserve.R for additional configuration NOT user R startup files
echo $RBIN CMD ${PRE}Rserve$PX --RS-conf $ROOT/code/rserve.conf --RS-source $ROOT/code/rserve.R --vanilla --no-save
$RBIN CMD ${PRE}Rserve$PX --RS-conf "$ROOT/code/rserve.conf" --RS-source "$ROOT/code/rserve.R" --vanilla --no-save
