#!/bin/sh
# script to start Rserve with the configuration FastRWeb/code/rserve.conf
# add -d if you want to start the debugging version

if [ -z "$ROOT" ]; then ## some auto-detection if ROOT is not set...
    for c in /data/ws /var/www/ws /var/FastRWeb /data/FastRWeb; do
	if [ -e "$c/code/rserve.conf" ]; then
	    ROOT="$c"
	    break
	fi
    done
fi

if [ -z "$ROOT" ]; then
    echo '' >&2
    echo ' ERROR: cannot determine ROOT - please set accordingly' >&2
    echo '' >&2
    exit 1
fi
export ROOT

if [ -z "$CONFROOT" ]; then
    echo "WARNING: assuming CONFROOT is $ROOT. Probably the wrong assumption!!" >&2
    CONFROOT=$ROOT
fi
export CONFROOT

if [ -z "$DATAROOT" ]; then
    echo "WARNING: assuming DATAROOT is $CONFROOT/.. . Probably the wrong assumption!!" >&2
    DATAROOT=$CONFROOT/..
fi
export DATAROOT

RBIN=R

if [ "$1" = -h ]; then
  echo ''
  echo " Usage: $0 [-d]"
  echo ''
  exit 0
fi
if [ "$1" = -d ]; then
  PX=.dbg
fi

CMDSTART="$RBIN CMD ${PRE}Rserve$PX --RS-conf $CONFROOT/rserve.conf --RS-source $CONFROOT/rserve.R --no-save"
echo $CMDSTART
$CMDSTART
