# -*- mode: ruby -*-
# vi: set ft=ruby :

GITHUB_CLIENT_ID = ENV["RCLOUD_GITHUB_CLIENT_ID"]
GITHUB_CLIENT_SECRET = ENV["RCLOUD_GITHUB_CLIENT_SECRET"]

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "..", "/data/rcloud"

  env = {
    GITHUB_CLIENT_ID: "#{GITHUB_CLIENT_ID}",
    GITHUB_CLIENT_SECRET: "#{GITHUB_CLIENT_SECRET}"
  }

  config.vm.provision "bootstrap", type: "shell", path: "bootstrap.sh"
  config.vm.provision "restart", type: "shell", path: "githubtoken.sh",
                      run: "always", env: env

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1096"
  end
end
