#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(realpath $(dirname "${BASH_SOURCE[0]}"))"
export ROOT=$(realpath $SCRIPT_DIR/..)
export R_LIBS=$(realpath $SCRIPT_DIR/../lib)
export R_LIBS_USER=$R_LIBS

if [ ! -d "$ROOT/run" ]; then mkdir -p "$ROOT/run"; fi

if [ ! -f $ROOT/conf/rcloud.conf ]; then
    echo "WARNING: conf/rcloud.conf not found, using rcloud.conf.docker";
    cp "$ROOT/conf/rcloud.conf.docker" "$ROOT/conf/rcloud.conf";
fi

if ! redis-cli ping; then  redis-server & fi

R --slave --no-restore --vanilla \
  --file="$ROOT/conf/run_rcloud.R" \
  --args "$ROOT/conf/rserve.conf"
