#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(realpath $(dirname "${BASH_SOURCE[0]}"))"
ROOT=$(realpath $SCRIPT_DIR/..)

kill $(cat "$ROOT/run/rserve.pid")
killall Rserve
killall redis-server
