name: rcloud-qap

services:
  rcloud-qap:
    image: rcloud-qap
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-qap
    ports:
      - "8080:8080"
    volumes:
      - rcloud-data:/data
      - rcloud-run:/run

  rserve-qap:
    image: rcloud-qap
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-rserve-qap

  sks:
    image: rcloud-sks
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-sks
    ports:
      - "4301:4301"


volumes:
  rcloud-data:
  rcloud-run:
