#!/bin/sh

: ${ROOT=/data/rcloud}
: ${RBIN=R}
export ROOT
RS=`echo 'cat(system.file("libs","Rserve",package="Rserve"))' | "$RBIN" --vanilla --slave`
R_LIBS=$ROOT/Rlib "$RBIN" CMD "$RS" --RS-conf "$ROOT/conf/scripts.conf" --no-save
