#!/bin/sh

ROOT=/data/rcloud
export ROOT

forward=`echo 'cat(system.file("libs","forward",package="Rserve"))'|R --vanilla --slave`

if [ -z "$forward" ]; then echo 'ERROR: cannot find proxy binary - maybe you need to install Rserve?' >&2; exit 1; fi

exec "$forward" -p 8080 -s "$ROOT/run/qap" -r "$ROOT/htdocs" -R "$ROOT/run/Rscripts" -u "$ROOT/run/ulog.proxy"
